services:
  db:
    image: mysql:5.7
    platform: linux/x86_64
    container_name: veldrin-db
    restart: unless-stopped
    env_file: .env
    volumes:
      - store_db_data:/var/lib/mysql

  wordpress:
    image: wordpress:php8.3-apache
    container_name: veldrin
    depends_on:
      - db
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./src:/var/www/html
    ports:
      - "8000:80"
    networks:
      proxy:
        aliases: [veldrin]
      default: {}
    labels:
      - "traefik.enable=false"

volumes:
  store_db_data:

networks:
  proxy:
    external: true
    name: proxy
